# Use henry/henry as user/password credentials
version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /docker-data-store/mongodb:/data/db
      - /docker-data-store/share:/data/share
    env_file:
      - mongodb.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - mongodb.env
